server:
  port: 8888   # web服务器在端口

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 全局配置jackson date-format 格式
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://192.168.
    username: test
    password: xxoo
    driver-class-name: com.mysql.jdbc.Driver